version: '3'
services:
  unifi-video:
    image: mgcrea/unifi-video:3
    container_name: unifi-video
    environment:
      - TZ=Europe/Paris
    network_mode: "host"
    privileged: true
    volumes:
      - ./data/lib:/var/lib/unifi-video:rw
      - ./data/log:/var/lib/unifi-video/logs:rw
      - ./data/videos:/var/lib/unifi-video/videos:rw
      - ./data/work:/usr/lib/unifi-video/work:rw
      - ./data/cache:/var/cache/unifi-video:rw
    ports:
      - "6666:6666"
      - "7080:7080/tcp"
      - "7443:7443/tcp"
      - "7440:7440"
      - "7442:7442"
      - "7445:7445"
      - "7446:7446"
      - "7447:7447"
    restart: always