# @url https://docs.docker.com/compose/yml/
# @cli docker run --privileged --rm -it mgcrea/unifi-video /bin/bash
# @cli docker-compose run unifi_video_controller /bin/bash

version: '3.1'
services:
  unifi_video_controller:
    image: mgcrea/unifi-video:3
    hostname: unifi_video
    container_name: unifi_video
    environment:
      - TZ=Europe/Paris
    network_mode: "bridge"
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    volumes:
      - ./data/lib:/var/lib/unifi-video
      - ./data/log:/var/log/unifi-video
      - ./data/work:/usr/lib/unifi-video/work
      - ./data/cache:/var/cache/unifi-video
    ports:
      - "1935:1935"
      - "6666:6666"
      - "7080:7080/tcp"
      - "7443:7443/tcp"
      - "7440:7440"
      - "7442:7442"
      - "7445:7445"
      - "7446:7446"
      - "7447:7447"
    restart: always
